[Merged by Bors] - Rework operator to meet the new architecture
stackabletech/hbase-operator pull request #110
Opened 2022-02-08 12:32 UTC by siegfriedweber

## Description

Operator migrated to the new structure which uses StatefulSets rather than direct Pod management.

[![Build Actions Status](https://ci.stackable.tech/job/HBase%20Operator%20Integration%20Tests%20(flex)/badge/icon?subject=Integration%20Tests)](https://ci.stackable.tech/view/02%20Component%20Tests%20(flex)/job/HBase%20Operator%20Integration%20Tests%20(flex)/9/)

Closes #43 

## Review Checklist
- [x] Code contains useful comments
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)
- [x] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2022-02-09 15:56 UTC, maltesander reviewed
Cluster was created successfully, no errors.
Some hints:
- We should reactivate the monitoring (jmx-exporter) since it was in before the rework as well
- Expose metrics ports (container and services)
- Readiness and liveness probes
- Region server http / ui port not exposed which makes it hard to get to the UI (16030)
- We could add the scraping label already?

2022-02-09 15:56 UTC, maltesander commented on rust/operator-binary/src/main.rs
> +                .map(erase_controller_result_type)
`.map(erase_controller_result_type)` not required for only one controller

2022-02-09 15:56 UTC, maltesander commented on rust/crd/src/lib.rs
>  pub const MANAGED_BY: &str = "hbase-operator";
`MANAGED_BY` not used

2022-02-09 15:56 UTC, maltesander commented on rust/operator-binary/src/hbase_controller.rs
> +        .build();
Can we add readiness and liveness probes?

2022-02-11 07:30 UTC, siegfriedweber commented on rust/operator-binary/src/main.rs
> +                .map(erase_controller_result_type)
removed

2022-02-11 07:30 UTC, siegfriedweber commented on rust/crd/src/lib.rs
>  pub const MANAGED_BY: &str = "hbase-operator";
removed

2022-02-11 07:30 UTC, siegfriedweber commented on rust/operator-binary/src/hbase_controller.rs
> +        .build();
added

2022-02-11 12:31 UTC, maltesander requested changes
Tested and works. Metrics up and running.
 
You can ignore the code comments (not that important)

But we need a full example (zookeeper cluster + hdfs + hdfs znode + hbase + hbase znode)

2022-02-11 14:15 UTC, siegfriedweber commented on rust/operator-binary/src/hbase_controller.rs
> +    ];
moved to the HbaseRole implementation

2022-02-11 14:15 UTC, siegfriedweber commented on rust/operator-binary/src/hbase_controller.rs
> +}
moved to the HbaseRole implementation

2022-02-11 14:19 UTC, siegfriedweber commented on rust/operator-binary/src/hbase_controller.rs
> +    };
Not moved to the HbaseRole implementation as discussed in the chat. The reason is that it would be necessary to also return if it is an HTTP port or not to choose the according action.

2022-02-11 15:00 UTC, maltesander approved these changes
LGTM.

2022-02-11 15:13 UTC, siegfriedweber commented
bors merge

2022-02-11 15:23 UTC, closed without merging