Phoenix tests
stackabletech/hbase-operator pull request #221
Opened 2022-08-01 15:44 UTC by adwk67

# Description

Added phoenix test using example files bundled with phoenix installation.

## Review Checklist

- [ ] Code contains useful comments
- [ ] CRD change approved (or not applicable)
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2022-08-15 11:57 UTC, sbernauer requested changes

2022-08-15 11:57 UTC, sbernauer commented on tests/test-definition.yaml
> +      - hbase-latest
I think here it is beneficial to test all available hbase versions

2022-08-15 11:59 UTC, sbernauer commented on docs/modules/ROOT/pages/usage.adoc
> +
```suggestion
```

2022-08-15 12:53 UTC, adwk67 commented on tests/test-definition.yaml
> +      - hbase-latest
We have the same phoenix bundle for all currently supported hbase versions, but you're right: here we are testing images rather than any operator code. I've started a jenkins run [here](https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hbase-operator-it-custom/27/console).

2022-08-15 13:28 UTC, sbernauer approved these changes
LGTM. Please wait with merging for test to succeed

2022-08-16 08:57 UTC, sbernauer approved these changes
LGTM when tests work

2022-08-19 16:46 UTC, adwk67 commented
#### Update 
The phoenix bundle includes client/server .jar files and two python scripts that serve as test utilities: `psql.py` and `sqlline.py`. Both of these wrap java commands that execute phoenix commands or launch the sqlline client, respectively. The integration tests originally called `psql.py `from another python script (which then parsed the result). This has been replaced with a shell script that does roughly the same, but with a more direct callout. In tests with parallel=1 (Hetzner), the run is now successful: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hbase-operator-it-custom/46/console

With parallel=4 (e.g. mk8s/Azure) the tests pass when just a subset are run, but not when all are included, which suggests that reducing the parallelism may improve things.

2022-08-22 06:51 UTC, sbernauer approved these changes
Thx for the detailed information!

2022-08-22 06:54 UTC, adwk67 commented
bors merge

2022-08-22 07:04 UTC, closed without merging