Getting started docs
stackabletech/hbase-operator pull request #235
Opened 2022-08-22 10:38 UTC by adwk67

# Description

Added getting started documentation. Closes #227.

## Review Checklist

- [ ] Code contains useful comments
- [ ] CRD change approved (or not applicable)
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2022-08-22 16:22 UTC, maltesander requested changes
Tested and works. Some findings:

- You can delete the ROOT/nav.doc link to the installation.adoc and the ROOT/pages/installation.adoc file.
- The getting_started module is missing in the antora.yaml
- I would refactor all the `Zookeeper` occurances in the text to `ZooKeeper` (be careful with the kind in the yaml files though)

2022-08-23 07:44 UTC, adwk67 commented on docs/modules/getting_started/pages/installation.adoc
> +----
Thanks! - corrected.

2022-08-23 07:44 UTC, adwk67 commented on docs/modules/getting_started/pages/index.adoc
> +* optional: Helm
Good point - `curl` is not needed locally but `jq` is: added accordingly.

2022-08-23 07:44 UTC, adwk67 commented on docs/modules/getting_started/examples/code/getting_started.sh.j2
> +# forward and connect to the superset instance to make sure it is up and running.
Done.

2022-08-23 07:48 UTC, adwk67 commented on docs/modules/getting_started/examples/code/hdfs.yaml
> +    log4j.appender.EventCounter=org.apache.hadoop.log.metrics.EventCounter
Done/removed.

2022-08-23 08:00 UTC, adwk67 commented
> Tested and works. Some findings:
> 
> * You can delete the ROOT/nav.doc link to the installation.adoc and the ROOT/pages/installation.adoc file.
> * The getting_started module is missing in the antora.yaml
> * I would refactor all the `Zookeeper` occurances in the text to `ZooKeeper` (be careful with the kind in the yaml files though)

Done.

2022-08-23 08:01 UTC, maltesander commented on docs/modules/getting_started/pages/first_steps.adoc
> +An alternative way to interact with HBase is to use the https://phoenix.apache.org/index.html[Phoenix] library that is pre-installed on the Stackable HBase image. Use the python utility `psql.py` to
I did not know this, can we add a hint where to find this?

2022-08-23 08:08 UTC, adwk67 commented on docs/modules/getting_started/pages/first_steps.adoc
> +An alternative way to interact with HBase is to use the https://phoenix.apache.org/index.html[Phoenix] library that is pre-installed on the Stackable HBase image. Use the python utility `psql.py` to
I've added a note re. location.

2022-08-23 08:15 UTC, maltesander approved these changes
LGTM.

2022-08-23 10:00 UTC, adwk67 commented
bors merge

2022-08-23 10:43 UTC, adwk67 commented
bors cancel

2022-08-23 10:44 UTC, adwk67 commented
bors merge

2022-08-23 10:53 UTC, closed without merging