feat: Support PodDisruptionBudgets
stackabletech/hbase-operator pull request #399
Opened 2023-09-29 07:05 UTC by sbernauer

# Description

*Please add a description here. This will become the commit message of the merge request later.*

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

2023-09-29 07:08 UTC, sbernauer commented on docs/modules/hbase/pages/usage-guide/concepts/pod-disruptions.adoc
> +TODO
Marker for docs

2023-09-29 07:08 UTC, sbernauer commented on rust/operator-binary/src/operations/pdb.rs
> +    1
Marker: We need a decision here :) CC @lfrancke

2023-09-29 08:47 UTC, sbernauer commented on rust/operator-binary/src/operations/pdb.rs
> +    zookeeper: &HbaseCluster,
marker to fix

2023-09-29 11:14 UTC, sbernauer commented
https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hbase-operator-it-custom/106/

2023-10-04 06:30 UTC, sbernauer commented on docs/modules/hbase/pages/usage-guide/concepts/pod-disruptions.adoc
> +TODO
@lfrancke what do you think of the following sentence?

We only allow a single RegionServer to be offline at any given time, regardless of the number of replicas or `roleGroups`. HBase replicates the regions of your tables across `<replication-factor>` RegionServers, where you can configure the replication factor for every table individually. As we can't make any assumptions about the replication factors of your tables, we are conservative here to reduce downtime.

2023-10-04 06:33 UTC, lfrancke commented on docs/modules/hbase/pages/usage-guide/concepts/pod-disruptions.adoc
> +TODO
No, HBase doesn't replicate the regions (at least not by default, it has a feature called read replica but very few people use it).

Suggestion: To have as little data unavailable at any given time we only allow a single RegionServer to be unavailable.

2023-10-04 06:41 UTC, sbernauer commented on docs/modules/hbase/pages/usage-guide/concepts/pod-disruptions.adoc
> +TODO
Thanks! To stick to the theme we use in other operators, is the following also ok?

We only allow a single RegionServer to be offline at any given time, regardless of the number of replicas or `roleGroups`, to have as little data unavailable as possible at any given time.

2023-10-04 06:42 UTC, lfrancke commented on docs/modules/hbase/pages/usage-guide/concepts/pod-disruptions.adoc
> +TODO
Works for me, yes!

2023-10-04 07:27 UTC, sbernauer commented on docs/modules/hbase/pages/usage-guide/concepts/pod-disruptions.adoc
> +TODO
Thanks!

2023-10-05 13:28 UTC, adwk67 requested changes
lgtm % comments

2023-10-05 13:28 UTC, adwk67 commented on docs/modules/hbase/pages/usage-guide/operations/graceful-shutdown.adoc
> +The efforts of implementing graceful shutdown for all products that have this functionality is tracked in
```suggestion
Outstanding implementation work for the graceful shutdowns of all products where this functionality is relevant is tracked in
```

2023-10-05 13:28 UTC, adwk67 commented on docs/modules/hbase/pages/usage-guide/operations/index.adoc
> +Please read on the xref:concepts:operations/index.adoc[Concepts page on Operations] with the necessary details to operate the platform in a production environment.
```suggestion
Please read the xref:concepts:operations/index.adoc[Concepts page on Operations] that contains the necessary details to operate the platform in a production environment.
```

2023-10-05 13:28 UTC, adwk67 commented on docs/modules/hbase/pages/usage-guide/operations/pod-disruptions.adoc
> +You can configure the allowed Pod disruptions for HBase nodes as described in xref:concepts:operations/pod_disruptions.adoc[].
```suggestion
You can configure the permitted Pod disruptions for HBase nodes as described in xref:concepts:operations/pod_disruptions.adoc[].
```

2023-10-05 13:57 UTC, adwk67 approved these changes

2023-10-05 14:33 UTC, merged