feat: Support graceful shutdown
stackabletech/hbase-operator pull request #402
Opened 2023-10-11 12:10 UTC by sbernauer

# Description

Part of https://github.com/stackabletech/issues/issues/357
Closes https://github.com/stackabletech/hbase-operator/issues/400

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

2023-10-16 12:05 UTC, sbernauer commented on docs/modules/hbase/pages/usage-guide/operations/graceful-shutdown.adoc
> +You can configure the graceful shutdown as described in xref:concepts:operations/pod_placement.adoc[].
```suggestion
You can configure the graceful shutdown as described in xref:concepts:operations/graceful_shutdown.adoc[].
```

2023-10-19 12:06 UTC, Techassi requested changes
Some minor nits.

2023-10-19 12:06 UTC, Techassi commented on docs/modules/hbase/pages/usage-guide/operations/graceful-shutdown.adoc
> +They go through the same mechanism as documented for the <<_masters>> above.
```suggestion
They use the same mechanism described above.
```

2023-10-19 12:06 UTC, Techassi commented on docs/modules/hbase/pages/usage-guide/operations/graceful-shutdown.adoc
> +They will also acknowledge the graceful shutdown with a message in the logs:
```suggestion
In contrast to the Master servers, they will, however, acknowledge the graceful shutdown with a message in the logs:
```

2023-10-19 12:06 UTC, Techassi commented on docs/modules/hbase/pages/usage-guide/operations/graceful-shutdown.adoc
> +They will also acknowledge the graceful shutdown with a message in the logs:
Maybe use the same phrasing as mentioned above.

2023-10-19 12:06 UTC, Techassi commented on rust/crd/src/lib.rs
> +    /// Time period Pods have to gracefully shut down, e.g. `30m`, `1h` or `2d`. Consult the operator documentation for details.
Add a newline between fields.

2023-10-19 12:06 UTC, Techassi commented on rust/operator-binary/src/hbase_controller.rs
> +    #[snafu(display("failed to configure graceful shutdown"))]
Add a newline between error variants.

2023-10-19 13:08 UTC, sbernauer commented on docs/modules/hbase/pages/usage-guide/operations/graceful-shutdown.adoc
> +As a default, masters have `20 minutes` to terminate gracefully.
+1 for shutdown

2023-10-19 13:10 UTC, sbernauer commented
Please have a look at https://github.com/stackabletech/hbase-operator/commit/5a274008ce793c0b2e3cd2b5ff84941cbb291655 and https://github.com/stackabletech/hdfs-operator/commit/153b2c205a0c330967110a28c2b1c168cb275290

2023-10-19 13:46 UTC, Techassi requested changes
Final nit :)

2023-10-19 13:46 UTC, Techassi commented on rust/crd/src/lib.rs
> +        let graceful_shutdown_timeout = match &self {
Add newline.

2023-10-19 13:47 UTC, sbernauer commented on rust/crd/src/lib.rs
> +        let graceful_shutdown_timeout = match &self {
done

2023-10-19 13:48 UTC, sbernauer commented
https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hbase-operator-it-custom/107/

2023-10-19 13:56 UTC, Techassi approved these changes

2023-10-31 16:56 UTC, siegfriedweber submitted a review, later dismissed
LGTM

2023-11-02 11:46 UTC, sbernauer commented
Final test run: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hbase-operator-it-custom/110/

2023-11-02 13:10 UTC, Techassi approved these changes

2023-11-02 13:15 UTC, sbernauer commented
Started https://ci.stackable.tech/job/hbase-operator-it-custom/111/

2023-11-02 14:37 UTC, sbernauer commented
Tests passed :rocket:

2023-11-02 14:43 UTC, merged