docs: Add example to pod placement
stackabletech/hbase-operator pull request #413
Opened 2023-11-07 14:12 UTC by sbernauer

# Description

*Please add a description here. This will become the commit message of the merge request later.*

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

2023-11-07 14:16 UTC, lfrancke requested changes

2023-11-07 14:16 UTC, lfrancke commented on docs/modules/hbase/pages/usage-guide/operations/pod-placement.adoc
> +1. Co-locate all the Hbase Pods (weight 20)
```suggestion
1. Co-locate all the HBase Pods (weight 20)
```

2023-11-07 14:16 UTC, lfrancke commented on docs/modules/hbase/pages/usage-guide/operations/pod-placement.adoc
> +2. Co-locate Hbase regionservers with the underlying HDFS datanodes (weight 50)
```suggestion
2. Co-locate HBase regionservers with the underlying HDFS datanodes (weight 50)
```

2023-11-07 14:16 UTC, lfrancke commented on docs/modules/hbase/pages/usage-guide/operations/pod-placement.adoc
> +3. Distribute all Pods within the same role (masters, region servers, rest servers) (weight 70)
```suggestion
3. Distribute all Pods within the same role (masters, regionservers, rest servers) (weight 70)
```

2023-11-07 14:16 UTC, lfrancke commented on docs/modules/hbase/pages/usage-guide/operations/pod-placement.adoc
> +xref:concepts:operations/pod_placement.adoc[] describes how you can configure pod placement in general.
Doesn't this look weird in a rendered version?
"Pod placement describes how you can configure pod placement in general."

2023-11-08 08:30 UTC, sbernauer commented on docs/modules/hbase/pages/usage-guide/operations/pod-placement.adoc
> +xref:concepts:operations/pod_placement.adoc[] describes how you can configure pod placement in general.
Agreed. b243684

2023-11-08 09:33 UTC, lfrancke commented on docs/modules/hbase/pages/usage-guide/operations/pod-placement.adoc
> +xref:concepts:operations/pod_placement.adoc[The concepts page on Pod Placement] describes how you can configure pod placement in general.
I'm sorry but: How does this look in a rendered version now?
I wanted to avoid the duplication of "Pod placement"
And: It should be "placement" not "Placement"

2023-11-08 10:12 UTC, sbernauer commented on docs/modules/hbase/pages/usage-guide/operations/pod-placement.adoc
> +xref:concepts:operations/pod_placement.adoc[The concepts page on Pod Placement] describes how you can configure pod placement in general.
Fixed lower and upper case.

Currently it reads

[The concepts page on Pod placement](http://foo) describes how you can configure Pod placement in general.

We could change it to e.g.

[This concepts page](http://foo) describes how you can configure Pod placement in general.

but I have been told to not have "click this" links, but instead tell the user where the link is pointing too.
But I don't have a strong opinion and let you decide

2023-11-08 10:22 UTC, lfrancke commented on docs/modules/hbase/pages/usage-guide/operations/pod-placement.adoc
> +xref:concepts:operations/pod_placement.adoc[The concepts page on Pod Placement] describes how you can configure pod placement in general.
My suggestion:

For general configuration of Pod placement, see the [Pod placement concepts] page.

2023-11-08 10:42 UTC, sbernauer commented on docs/modules/hbase/pages/usage-guide/operations/pod-placement.adoc
> +xref:concepts:operations/pod_placement.adoc[The concepts page on Pod Placement] describes how you can configure pod placement in general.
Applied in 2996c2f

2023-11-08 10:56 UTC, lfrancke commented on docs/modules/hbase/pages/usage-guide/operations/pod-placement.adoc
> +3. Distribute all Pods within the same role (masters, regionservers, rest servers) (weight 70)
Sorry, reading this again now, I have a new suggestion.


```suggestion
1. Co-locate all the HBase Pods (weight 20)
2. Co-locate HBase regionservers with the underlying HDFS datanodes (weight 50)
3. Distribute all Pods within the same role across nodes so multiple instances don't end up on the same Kubernetes node (masters, regionservers, rest servers) (weight 70)
```

Point 1 needs clarification but I don't know exactly how. What is it we do exactly there?
And we should point out (I thought we did somewhere) that this is "only" preferred not required

2023-11-13 12:54 UTC, sbernauer commented on docs/modules/hbase/pages/usage-guide/operations/pod-placement.adoc
> +3. Distribute all Pods within the same role (masters, regionservers, rest servers) (weight 70)
See 30eba1a

2023-11-13 12:56 UTC, lfrancke commented on docs/modules/hbase/pages/usage-guide/operations/pod-placement.adoc
> +3. Distribute all Pods within the same role (masters, regionservers, rest servers) (weight 70)
Thank you. But what does the first point actually mean?
"Co-locate al the HBase Pods"

2023-11-13 15:53 UTC, sbernauer commented on docs/modules/hbase/pages/usage-guide/operations/pod-placement.adoc
> +3. Distribute all Pods within the same role (masters, regionservers, rest servers) (weight 70)
Its the first rule in the example below
```
affinity:
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: cluster-name
            app.kubernetes.io/name: hbase
        topologyKey: kubernetes.io/hostname
      weight: 20
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: master
            app.kubernetes.io/instance: cluster-name
            app.kubernetes.io/name: hbase
        topologyKey: kubernetes.io/hostname
      weight: 70
```
I just pulls all HBase Pods together, so that e.g. hbase master + regionserver + restserver run on the same node to reduce latency.

2023-11-13 18:54 UTC, lfrancke approved these changes

2023-11-14 08:37 UTC, sbernauer commented
Thanks!

2023-11-14 08:40 UTC, merged