Document the snapshot export to S3
stackabletech/hbase-operator pull request #489
Opened 2024-04-15 15:17 UTC by siegfriedweber

# Description

Document the snapshot export to S3

Documents #486 

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs-style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

2024-04-16 13:57 UTC, adwk67 requested changes

2024-04-16 13:57 UTC, adwk67 commented on docs/modules/hbase/pages/usage-guide/snapshot-export.adoc
> +The script `export-snapshot-to-s3` facilitates the export, by providing the according classpath, extending the Hadoop configuration with the S3 configuration, and calling `hbase snapshot export`.
```suggestion
The script `export-snapshot-to-s3` facilitates the export, by providing the associated classpath, extending the Hadoop configuration with the S3 configuration, and calling `hbase snapshot export`.
```

2024-04-16 13:57 UTC, adwk67 commented on docs/modules/hbase/pages/usage-guide/snapshot-export.adoc
> +include::example$usage-guide/snapshot-export-job.yaml[]
I think we have to split the script here, as at least in my IDE it only renders the last part (the secret).

2024-04-16 15:16 UTC, siegfriedweber commented on docs/modules/hbase/pages/usage-guide/snapshot-export.adoc
> +include::example$usage-guide/snapshot-export-job.yaml[]
I cannot reproduce this issue with Antora. Nevertheless, I put the YAML documents into separate files. Please try again, if it works now in your IDE.

2024-04-16 15:31 UTC, adwk67 commented on docs/modules/hbase/pages/usage-guide/snapshot-export.adoc
> +include::example$usage-guide/snapshot-export-job.yaml[]
Yes, this works for me now in my IDE (Rust Rover). Thanks!

2024-04-16 15:32 UTC, adwk67 approved these changes

2024-04-16 15:35 UTC, merged

2024-04-23 11:07 UTC, lfrancke commented
Can you please include a link to the generated nightly docs?

2024-04-23 12:21 UTC, fhennig commented
https://docs.stackable.tech/home/nightly/hbase/usage-guide/snapshot-export