feat(test): make it easy to test custom images
stackabletech/hbase-operator pull request #506
Opened 2024-06-04 12:12 UTC by razvan

# Description

Needed for: https://github.com/stackabletech/hbase-operator/issues/488

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs-style-guide).
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs-style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

2024-06-12 07:05 UTC, razvan commented
[CI](https://ci.stackable.tech/job/hbase-operator-it-custom/147/) (almost green)

```
--- FAIL: kuttl (1725.57s)
    --- FAIL: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/profiling_hbase-2.6.0,docker.stackable.tech_sandbox_hbase_2.6.0-stackable0.0.0-dev_hdfs-latest-3.3.6_zookeeper-latest-3.9.1_openshift-false (338.61s)
        --- PASS: kuttl/harness/resources_hbase-latest-2.4.17_hdfs-latest-3.3.6_zookeeper-latest-3.9.1_openshift-false (538.55s)
        --- PASS: kuttl/harness/smoke_hbase-2.6.0,docker.stackable.tech_sandbox_hbase_2.6.0-stackable0.0.0-dev_hdfs-3.3.6_zookeeper-3.8.3_listener-class-external-unstable_openshift-false (552.05s)
        --- PASS: kuttl/harness/logging_hbase-2.6.0,docker.stackable.tech_sandbox_hbase_2.6.0-stackable0.0.0-dev_hdfs-latest-3.3.6_zookeeper-latest-3.9.1_openshift-false (227.43s)
        --- PASS: kuttl/harness/smoke_hbase-2.6.0,docker.stackable.tech_sandbox_hbase_2.6.0-stackable0.0.0-dev_hdfs-3.3.6_zookeeper-3.8.3_listener-class-cluster-internal_openshift-false (507.46s)
        --- FAIL: kuttl/harness/kerberos_hbase-2.6.0,docker.stackable.tech_sandbox_hbase_2.6.0-stackable0.0.0-dev_hdfs-latest-3.3.6_zookeeper-latest-3.9.1_krb5-1.21.1_listener-class-cluster-internal_kerberos-realm-PROD.MYCORP_kerberos-backend-mit_openshift-false (961.71s)
        --- PASS: kuttl/harness/snapshot-export_hbase-2.6.0,docker.stackable.tech_sandbox_hbase_2.6.0-stackable0.0.0-dev_hdfs-latest-3.3.6_zookeeper-latest-3.9.1_openshift-false (442.52s)
        --- PASS: kuttl/harness/orphaned_resources_hbase-latest-2.4.17_hdfs-latest-3.3.6_zookeeper-latest-3.9.1_openshift-false (247.75s)
        --- PASS: kuttl/harness/cluster-operation_hbase-latest-2.4.17_hdfs-latest-3.3.6_zookeeper-latest-3.9.1_openshift-false (271.48s)
        --- FAIL: kuttl/harness/opa_hbase-opa-2.6.0,docker.stackable.tech_sandbox_hbase_2.6.0-stackable0.0.0-opa_hdfs-latest-3.3.6_zookeeper-latest-3.9.1_krb5-1.21.1_kerberos-realm-PROD.MYCORP_openshift-false (758.92s)
        --- PASS: kuttl/harness/kerberos_hbase-2.6.0,docker.stackable.tech_sandbox_hbase_2.6.0-stackable0.0.0-dev_hdfs-latest-3.3.6_zookeeper-latest-3.9.1_krb5-1.21.1_listener-class-external-unstable_kerberos-realm-PROD.MYCORP_kerberos-backend-mit_openshift-false (878.39s)
FAIL
ERROR:root:kuttl failed
```

2024-06-14 12:08 UTC, razvan commented
[CI](https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hbase-operator-it-custom/154/)

2024-06-24 13:38 UTC, sbernauer reviewed
Not a complete review, just giving an early feedback during development, nothing urgent :sweat_smile:

2024-06-24 13:38 UTC, sbernauer commented on rust/operator-binary/src/security/opa.rs
> +pub enum Error {
Can we please have an Error entry that says something like "opa-authorizer only supported starting with HBAse version 2.6.0" and error out in case the HBase version is too old?

2024-06-24 13:38 UTC, sbernauer commented on tests/release.yaml
> +        operatorVersion: 0.0.0-pr506
Reminder to turn back

2024-06-24 13:38 UTC, sbernauer commented on CHANGELOG.md
> +
```suggestion

- Added support for HBase 2.6.0 ([#506]).
```

2024-06-24 13:38 UTC, sbernauer commented on docs/modules/hbase/examples/rego/hbase.rego
> +        "resource": "developers:",
I would prefer if the resource would state what resource you grant permissions on (similar to [hdfs-op](https://github.com/stackabletech/hdfs-operator/blob/05ab1d78d930b46928e10ff9fcbd8ecc7bd195fa/tests/templates/kuttl/kerberos/12-rego-rules.txt.j2#L253))
So basically something like `hbase:namespace:foo` and `hbase:table:foo.mytable` and e.g. for all tables in the foo namespace `hbase:table:foo.*` or for *all* tables `hbase:table:.*`

2024-06-24 13:38 UTC, sbernauer commented on tests/templates/kuttl/logging/04-install-hbase.yaml.j2
> +    appender.FILE.fileName = /stackable/log/hbase/spark.log4j2.xml
Is this filename correct? ;)

2024-06-24 14:24 UTC, razvan commented on tests/templates/kuttl/logging/04-install-hbase.yaml.j2
> +    appender.FILE.fileName = /stackable/log/hbase/spark.log4j2.xml
Yes, the repo is wrong :)

Fixed https://github.com/stackabletech/hbase-operator/pull/506/commits/44224b0d29fb37faae7a8b4f523a700375510009

2024-06-25 06:02 UTC, sbernauer commented on tests/templates/kuttl/logging/04-install-hbase.yaml.j2
> +    appender.FILE.fileName = /stackable/log/hbase/spark.log4j2.xml
Thanks!

2024-06-26 15:48 UTC, razvan commented on docs/modules/hbase/examples/rego/hbase.rego
> +        "resource": "developers:",
Done https://github.com/stackabletech/hbase-operator/pull/506/commits/67e263575c8621c6d5549f6b74799fab7f57675e

2024-07-11 12:21 UTC, razvan commented
CI: https://ci.stackable.tech/view/06%20Replicated/job/hbase-operator-it-replicated/17/

2024-07-12 07:45 UTC, razvan commented on tests/release.yaml
> +        operatorVersion: 0.0.0-pr506
Done https://github.com/stackabletech/hbase-operator/pull/506/commits/005b908d033dfba154e46b9a1d1e2b0540d35393

2024-07-12 09:25 UTC, lfrancke requested changes

2024-07-12 09:25 UTC, lfrancke commented on docs/modules/hbase/pages/usage-guide/security.adoc
> +Authorization using the Open Policy Agent (OPA) is supported.
I think we should have an INFO box mentioning that this is only supported as of 2.6 which is experimental right now.

2024-07-12 09:25 UTC, lfrancke commented on docs/modules/hbase/pages/usage-guide/security.adoc
> +A custom https://github.com/stackabletech/hbase-opa-authorizer[access controller CoProcessor] delegates authorization decisions to OPA.
```suggestion
A custom https://github.com/stackabletech/hbase-opa-authorizer[access controller coprocessor] delegates authorization decisions to OPA.
```

2024-07-12 09:25 UTC, lfrancke commented on docs/modules/hbase/pages/usage-guide/security.adoc
> +Authorization configurations is split in two parts:
```suggestion
Authorization configuration is split in two parts:
```

2024-07-12 09:25 UTC, lfrancke commented on docs/modules/hbase/pages/usage-guide/security.adoc
> +The current rego rules ignore file ownership and permissions, and ACLs are persisted in neither ZooKeeper nor internal HBase tables.
```suggestion
The current rego rules ignore file ownership and permissions, and ACLs are persisted neither in ZooKeeper nor internal HBase tables.
```

2024-07-12 09:25 UTC, lfrancke commented on docs/modules/hbase/pages/usage-guide/security.adoc
> +Instead, HBase will send a request detailing who (e.g. `alice/test-hbase-permissions.default.svc.cluster.local@CLUSTER.LOCAL`) is trying to execute what type of action (e.g. `READ`, `WRITE`, `CREATE`
```suggestion
Instead, HBase will send a request detailing who (e.g. `alice/test-hbase-permissions.default.svc.cluster.local@CLUSTER.LOCAL`) is trying to execute what type of action (e.g. `READ`, `WRITE`, `CREATE` or `ADMIN`) on what namespace or table (e.g. `developers:`, `developers/table1`) to OPA.
```

2024-07-12 09:25 UTC, lfrancke commented on docs/modules/hbase/pages/usage-guide/security.adoc
> +OPA then makes a decision if this action is allowed or not.
```suggestion
OPA then makes a decision whether this action is allowed or not.
```

2024-07-12 09:25 UTC, lfrancke commented on docs/modules/hbase/pages/usage-guide/security.adoc
> +Instead of using the HBase shell to grant or revoke rights to users, you can go to your IaC Git repository and add a rego rule entry specifying what a specific user is allowed to do to which specific
This makes assumptions.
I think we should write something along the lines of 

```suggestion
Instead of using the HBase shell to grant or revoke rights to users, you can create rules for OPA using the Rego language to define what a specific user is allowed or not allowed to do to.
```

2024-07-12 09:25 UTC, lfrancke commented on docs/modules/hbase/pages/usage-guide/security.adoc
> +There is complete file shown below, together with a list of test cases.
```suggestion
There is a complete file shown below, together with a list of test cases.
```

2024-07-12 09:25 UTC, lfrancke commented on docs/modules/hbase/pages/usage-guide/security.adoc
> +PASS: 11/11
Does this work? The syntax highlighting in the Github UI suggests that the previous dashes already ended the Asciidoc block.
Have you tried rendering this?

2024-07-12 09:25 UTC, lfrancke commented on docs/modules/hbase/partials/supported-versions.adoc
> +- 2.4.17 (Deprecated)
```suggestion
- 2.6.0 (Experimental)
- 2.4.18 (LTS)
- 2.4.17 (Deprecated)
```

2024-07-12 09:25 UTC, lfrancke commented on tests/templates/kuttl/profiling/run-profiler.py
> +        r'/prof-output-hbase/async-prof-pid-\d+-(itimer-\d+.flamegraph|cpu-\d+.html)'
Do we need to test this again/is this comment still valid?
I applied a patch so that flamegraph should be the default

2024-07-12 09:25 UTC, lfrancke commented on tests/test-definition.yaml
> +      - 2.6.0,docker.stackable.tech/sandbox/hbase:2.6.0-stackable0.0.0-dev
Should this be in here?

2024-07-12 09:40 UTC, razvan commented on tests/test-definition.yaml
> +      - 2.6.0,docker.stackable.tech/sandbox/hbase:2.6.0-stackable0.0.0-dev
fixed https://github.com/stackabletech/hbase-operator/pull/506/commits/ac80b16b594c641bff70b2d164b6cb99c483773e

2024-07-12 09:40 UTC, razvan commented on docs/modules/hbase/pages/usage-guide/security.adoc
> +PASS: 11/11
fixed https://github.com/stackabletech/hbase-operator/pull/506/commits/ac80b16b594c641bff70b2d164b6cb99c483773e

2024-07-12 09:40 UTC, razvan commented on docs/modules/hbase/pages/usage-guide/security.adoc
> +Authorization using the Open Policy Agent (OPA) is supported.
fixed https://github.com/stackabletech/hbase-operator/pull/506/commits/ac80b16b594c641bff70b2d164b6cb99c483773e

2024-07-12 10:19 UTC, lfrancke requested changes

2024-07-12 10:19 UTC, lfrancke commented on docs/modules/hbase/pages/usage-guide/security.adoc
> +NOTE: This is an exprimental feature available from HBase version 2.6.0 upwards.
```suggestion
NOTE: This is an experimental feature available from HBase version 2.6.0 upwards.
```

2024-07-12 10:19 UTC, lfrancke commented on docs/modules/hbase/pages/usage-guide/security.adoc
> +We provide a more representative rego rule in our integration tests and in the aforementioned co-processor repository.
```suggestion
We provide a more representative rego rule in our integration tests and in the aforementioned coprocessor repository.
```

2024-07-12 10:20 UTC, lfrancke approved these changes

2024-07-12 10:34 UTC, merged