test(omid): added omid kuttl test
stackabletech/hbase-operator pull request #515
Opened 2024-06-17 16:21 UTC by razvan

# Description

*Please add a description here. This will become the commit message of the merge request later.*

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs-style-guide).
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs-style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

2024-06-18 10:24 UTC, sbernauer commented on tests/templates/kuttl/omid/00-limit-range.yaml
> +        memory: 5
```suggestion
        memory: 1
```
In the other tests we use `1` to make sure we don't over-commit memory. It would be great if this would work here as well

2024-06-18 10:34 UTC, razvan commented on tests/templates/kuttl/omid/00-limit-range.yaml
> +        memory: 5
Yes, we cannot do this here because Omid requires much more memory than all others

2024-06-18 10:45 UTC, razvan commented on tests/templates/kuttl/omid/00-limit-range.yaml
> +        memory: 5
Ah, that's the ration between request and limit per container **not** between containers.

2024-06-18 11:04 UTC, razvan commented
:green_circle:  CI : https://ci.stackable.tech/job/hbase-operator-it-replicated/7/

2024-06-18 12:36 UTC, sbernauer requested changes
Did a complete review this time

2024-06-18 12:36 UTC, sbernauer commented on tests/templates/kuttl/omid/10-assert.yaml
> +  name: install-zk
AFAIK this field does not exist
```suggestion
```

2024-06-18 12:36 UTC, sbernauer commented on tests/templates/kuttl/omid/20-assert.yaml
> +  name: install-hdfs
```suggestion
```

2024-06-18 12:36 UTC, sbernauer commented on tests/templates/kuttl/omid/30-install-hbase.yaml.j2
> +        replicas: 2
Can we save some memory by only using a single rs and webserver?

2024-06-18 12:36 UTC, sbernauer commented on tests/templates/kuttl/omid/50-setup-example-tx-table.yaml
> +  name: examples-tx-table
```suggestion
```

2024-06-18 12:36 UTC, sbernauer commented on tests/templates/kuttl/omid/40-install-omid.yaml.j2
> +---
I would leave the review of this file to @soenkeliebau, as it differs from the one our customer is using and I have no clue about omid.

2024-06-18 12:57 UTC, razvan commented on tests/templates/kuttl/omid/10-assert.yaml
> +  name: install-zk
These were copy&pasta from the smoke test.

2024-06-19 05:03 UTC, sbernauer commented on tests/templates/kuttl/omid/30-install-hbase.yaml.j2
> +        replicas: 2
Many thanks!

2024-06-19 05:05 UTC, sbernauer submitted a review, later dismissed
LGTM % actual omid Pod & config review

2024-06-19 10:18 UTC, razvan commented
@sbernauer : had to update the test definition to [not use](https://github.com/stackabletech/hbase-operator/pull/515/commits/aadb2bf4f9ba2682b0e726bcbf0deaeb24349899) the sandbox image.

2024-06-20 06:42 UTC, merged

2024-06-20 11:34 UTC, sbernauer commented
@razvan I'm a bit surprised you were able to merge this with unresolved conversations :O
Did @soenkeliebau get a chance to have a look a the omid Pod?

2024-06-20 11:43 UTC, razvan commented
Looks like a comment doesn't count as _conversation_. I pinged him

2024-06-20 13:30 UTC, sbernauer commented
Interesting. Thanks!