feat(regionserver): add graceful shutdown configuration
stackabletech/hbase-operator pull request #570
Opened 2024-10-02 11:39 UTC by razvan

Extract region configuration into it's own structure. Refactor the lib and controller modules to work with the new structure in a slightly generic way.

# Description

part of: <https://github.com/stackabletech/hbase-operator/issues/508>

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

2024-10-17 15:16 UTC, NickLarsenNZ reviewed
Partial review

2024-10-17 15:16 UTC, NickLarsenNZ commented on docs/modules/hbase/pages/usage-guide/operations/graceful-shutdown.adoc
> +        extraOpts: ["--designatedFile", "/path/to/designatedFile"] <4>
Remove the trailing commas, and comment the numeric refs

```suggestion
        runBeforeShutdown: true # <1> 
        maxThreads: 5 # <2> 
        ack: false # <3>
        extraOpts: ["--designatedFile", "/path/to/designatedFile"] # <4>
```

2024-10-17 15:16 UTC, NickLarsenNZ commented on docs/modules/hbase/pages/usage-guide/operations/graceful-shutdown.adoc
> +<2>: Maximum number of threads to use for moving regions. Default is 1.
Is there a hint how this value should be set? Eg: number of servers?

2024-10-17 15:16 UTC, NickLarsenNZ commented on docs/modules/hbase/pages/usage-guide/operations/graceful-shutdown.adoc
> +<4>: Extra options to pass to the region mover tool.
Maybe add a link to valid options (or maybe they're covered already?)

2024-10-17 15:16 UTC, NickLarsenNZ commented on rust/crd/src/affinity.rs
> +            .unwrap()
Need to handle this error (or use expect if wr are guaranteeing it will not fail).

2024-10-17 15:16 UTC, NickLarsenNZ commented on rust/crd/src/lib.rs
> +const DEFAULT_REGION_MOVER_DELTA_TO_SHUTDOWN: Duration = Duration::from_minutes_unchecked(1);
I think this should be enforced in code (unless there is an obvious reason why not).

```suggestion
const DEFAULT_REGION_MOVER_TIMEOUT: Duration = Duration::from_minutes_unchecked(59); 
const DEFAULT_REGION_MOVER_DELTA_TO_SHUTDOWN: Duration = Duration::from_minutes_unchecked(1);
const DEFAULT_REGION_SERVER_GRACEFUL_SHUTDOWN_TIMEOUT: Duration = DEFAULT_REGION_MOVER_TIMEOUT + DEFAULT_REGION_MOVER_DELTA_TO_SHUTDOWN;
      
 
```

2024-10-17 16:00 UTC, razvan commented on docs/modules/hbase/pages/usage-guide/operations/graceful-shutdown.adoc
> +<2>: Maximum number of threads to use for moving regions. Default is 1.
I suppose it depends on the number of regions,  servers to distribute the regions to, total row count and what not.

As usual : it's complicated and if you don't have performance problems, don't touch it!

"1" is the default region mover it's self uses.

2024-10-17 16:07 UTC, razvan commented on docs/modules/hbase/pages/usage-guide/operations/graceful-shutdown.adoc
> +<4>: Extra options to pass to the region mover tool.
I couldn't find any documentation on this tool. I used the source.

2024-10-17 16:11 UTC, razvan commented on rust/crd/src/affinity.rs
> +            .unwrap()
The convention we used since the beginning was that we can just `unwrap()` in tests.

2024-10-21 06:57 UTC, razvan commented
:green_circle: CI: https://testing.stackable.tech/job/hbase-operator-it-custom/29/

2024-10-21 07:12 UTC, NickLarsenNZ commented on docs/modules/hbase/pages/usage-guide/operations/graceful-shutdown.adoc
> +<2>: Maximum number of threads to use for moving regions. Default is 1.
In any case, there probably should be some guidance rather than leaving it ambiguous.

2024-10-21 07:13 UTC, NickLarsenNZ commented on docs/modules/hbase/pages/usage-guide/operations/graceful-shutdown.adoc
> +<4>: Extra options to pass to the region mover tool.
Maybe we ca give a hint where to find the extra options in the source code?

2024-10-21 07:13 UTC, NickLarsenNZ commented on rust/crd/src/affinity.rs
> +            .unwrap()
My bad, I missed that it was a test.

2024-10-21 08:32 UTC, razvan commented on docs/modules/hbase/pages/usage-guide/operations/graceful-shutdown.adoc
> +<4>: Extra options to pass to the region mover tool.
Done: https://github.com/stackabletech/hbase-operator/pull/570/commits/7e118ab65529531e68cc4091295d056047be98ca

2024-10-21 08:32 UTC, razvan commented on docs/modules/hbase/pages/usage-guide/operations/graceful-shutdown.adoc
> +<2>: Maximum number of threads to use for moving regions. Default is 1.
I'll have to defer to the experts then.

2024-10-23 08:53 UTC, sbernauer requested changes
Ideally I would like to do a review, but I'm not sure if I will get to it, sorry!
One rather important thing is that we should use the Fragment mechanism for the RegionMover struct.
So something along the lines of (but only crafted that during a meeting :see_no_evil: )
```rust
#[derive(Clone, Debug, Default, Fragment, JsonSchema, PartialEq)]
#[fragment_attrs(
    derive(
        Clone,
        Debug,
        Default,
        Deserialize,
        Merge,
        JsonSchema,
        PartialEq,
        Serialize
    ),
    serde(rename_all = "camelCase")
)]
pub struct RegionMover {
    /// Move local regions to other servers before terminating a region server's pod.
    run_before_shutdown: Option<bool>,

    /// Maximum number of threads to use for moving regions.
    max_threads: Option<u16>,

    /// If enabled (default), the region mover will confirm that regions are available on the
    /// source as well as the target pods before and after the move.
    ack: Option<bool>,

    /// Additional options to pass to the region mover.
    extra_opts: Option<CliOpts>,
}

// TODO: Copy docs from StackableNodeSelector
#[derive(Clone, Debug, Eq, Deserialize, JsonSchema, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
#[schemars(deny_unknown_fields)]
pub struct CliOpts {
    #[serde(flatten)]
    pub cli_opts: Vec<String>,
}

impl Atomic for CliOpts {}
```

2024-10-23 09:53 UTC, razvan commented
> One rather important thing is that we should use the Fragment mechanism for the RegionMover struct.

Not disagreeing, but what is the benefit against just implementing Merge for it (as it's already done) ?

It seems to me like a lot more (quirky) code would be needed to achieve the same thing.

2024-10-24 13:28 UTC, siegfriedweber requested changes

2024-10-24 13:28 UTC, siegfriedweber commented on rust/operator-binary/src/hbase_controller.rs
> -            cp {HBASE_LOG_CONFIG_TMP_DIR}/{log4j_properties_file_name} {CONFIG_DIR_NAME}
It should be mentioned at the definitions of the constants that these directories are also hard-coded in the hbase-entrypoint.sh file. They cannot be relocated by just adapting the constants.

2024-10-24 13:43 UTC, sbernauer commented on tests/templates/kuttl/shutdown/00-limit-range.yaml
I personally think it's never a bad idea to include it. E.g. to detect we are not missing resources on a git-sync container (which let's say is not present in smoke) or similar.
But no strong opinion, I'll let you decide ;)

2024-10-24 14:14 UTC, siegfriedweber requested changes

2024-10-24 14:14 UTC, siegfriedweber commented on rust/operator-binary/src/hbase_controller.rs
> +            ),
Why is not just `localhost` used for `--regionserverhost`? You would avoid hard-coding `cluster.local` here.

2024-10-25 09:30 UTC, siegfriedweber commented on rust/operator-binary/src/hbase_controller.rs
> +            ),
The integration test runs successfully with `--regionserverhost localhost:${HBASE_ROLE_SERVICE_PORT}` as well as `--regionserverhost ${HOSTNAME}:${HBASE_ROLE_SERVICE_PORT}`. So, if the test covers all cases, it should be okay to use `localhost`.

2024-10-25 09:33 UTC, siegfriedweber commented on tests/templates/kuttl/shutdown/00-limit-range.yaml
Then let's keep it.

2024-10-25 10:14 UTC, razvan commented on rust/operator-binary/src/hbase_controller.rs
> +            ),
For the record, together we ran the mover manually with `localhost` and it didn't in fact move any regions.

2024-10-25 13:37 UTC, siegfriedweber commented on rust/operator-binary/src/hbase_controller.rs
> +            ),
The integration test was successful with `localhost` because the master performed a transition of all regions to the available region server. This must be prevented.

2024-10-25 13:54 UTC, siegfriedweber requested changes

2024-10-25 13:54 UTC, siegfriedweber commented on tests/templates/kuttl/shutdown/30-install-hbase.yaml.j2
> +            hbase.regionserver.wal.codec: "org.apache.hadoop.hbase.regionserver.wal.IndexedWALEditCodec"
```suggestion
          hbase-site.xml:
            # Prevent the master from re-assigning the region when the region server is
            # gone. Otherwise, the test case would not fail if the region mover fails. The
            # default retainment wait period is larger than the test step timeout. This
            # works only for HBase 2.6 (https://issues.apache.org/jira/browse/HBASE-27551).
            hbase.master.scp.retain.assignment: "true"
            hbase.master.scp.retain.assignment.force: "true"
```

2024-10-28 07:58 UTC, razvan commented on tests/templates/kuttl/shutdown/30-install-hbase.yaml.j2
> +            hbase.regionserver.wal.codec: "org.apache.hadoop.hbase.regionserver.wal.IndexedWALEditCodec"
Thanks. https://github.com/stackabletech/hbase-operator/pull/570/commits/19fed55e414a207e8b72b89ee58d4ef42f2b2231

2024-10-28 08:16 UTC, razvan commented on rust/operator-binary/src/hbase_controller.rs
> -            cp {HBASE_LOG_CONFIG_TMP_DIR}/{log4j_properties_file_name} {CONFIG_DIR_NAME}
Done https://github.com/stackabletech/hbase-operator/pull/570/commits/6f087dbc584f3ef7a95c107c93ecc7fb8144f225

2024-10-28 08:16 UTC, razvan commented on rust/operator-binary/src/hbase_controller.rs
> +    // This env var is set for all roles to avoid bash's "unbound variable" errors
Thanks. I'll keep that in mind for the future.

2024-10-28 08:17 UTC, razvan commented on tests/templates/kuttl/shutdown/30-install-hbase.yaml.j2
> +        configOverrides:
Removed https://github.com/stackabletech/hbase-operator/pull/570/commits/0f32e59e386a515379240cdf142ed36c4bbea122

2024-10-28 08:18 UTC, razvan commented on rust/crd/src/lib.rs
> +impl Atomic for RegionMover {}
Done in https://github.com/stackabletech/hbase-operator/pull/570/commits/109e87765a5af3c9cd68944a390d5833a1e2fbe0 and https://github.com/stackabletech/hbase-operator/pull/570/commits/05f43037c3c5a00a900d57622eded1dc8dae32b0

2024-10-29 14:38 UTC, siegfriedweber requested changes

2024-10-29 14:38 UTC, siegfriedweber commented on rust/crd/src/lib.rs
> +                // TODO: is unwrap_or() the correct way to do it ? (same below)
The atomic fields in `RegionMover` should not be optional. In the `RegionMoverFragment`, they are automatically made optional. So, if the `Option`s are removed then the CRD still does not change. The `Default` implementation would have to be changed but as it is not used anyway, it can also be removed. With non-optional fields, `unwrap_or` is not necessary here.

2024-10-30 13:50 UTC, razvan commented on rust/crd/src/lib.rs
> +                // TODO: is unwrap_or() the correct way to do it ? (same below)
[done](https://github.com/stackabletech/hbase-operator/pull/570/commits/d6d5fe4c2452ab003c1eb79ff3808e6929cbf75e)

2024-10-30 13:50 UTC, razvan commented on rust/crd/src/lib.rs
> +        // as expected (i.e. users can override the env var value).
[done](https://github.com/stackabletech/hbase-operator/pull/570/commits/d6d5fe4c2452ab003c1eb79ff3808e6929cbf75e)

2024-10-31 18:56 UTC, siegfriedweber submitted a review, later dismissed
LGTM

2025-01-17 11:15 UTC, razvan commented
Updated and it now requires https://github.com/stackabletech/docker-images/pull/974

2025-02-05 16:22 UTC, siegfriedweber requested changes

2025-02-05 16:22 UTC, siegfriedweber commented on tests/templates/kuttl/shutdown/30-install-hbase.yaml.j2
> +            # This gives the region mover enoug time to run and ensures that masters do not interfere.
```suggestion
            # This gives the region mover enough time to run and ensures that masters do not interfere.
```

2025-02-05 16:22 UTC, siegfriedweber commented on tests/test-definition.yaml
> +      - 2.6.0,docker.stackable.tech/sandbox/hbase:2.6.0-pr974
stackabletech/docker-images#974 is merged and these temporary changes can be reverted.

2025-02-05 17:48 UTC, razvan commented on CHANGELOG.md
> +
Thanks, [done](https://github.com/stackabletech/hbase-operator/pull/570/commits/76001c51802c42ef9b1603b28c06d2ea92b46029)

2025-02-06 08:18 UTC, siegfriedweber approved these changes
LGTM

2025-02-06 08:42 UTC, razvan commented
> LGTM

Thanks!

2025-02-06 08:45 UTC, merged

2025-02-07 10:45 UTC, sbernauer commented on deploy/helm/hbase-operator/crds/crds.yaml
> +                          type: string
I think this should not be added again (applies to all roles).
https://github.com/stackabletech/hbase-operator/pull/620 removed it, can you please remove it again?

2025-02-07 10:45 UTC, sbernauer commented on rust/operator-binary/src/config/jvm.rs
> +/// Arguments that go into `HBASE_OPTS`, so *not* the heap settings (which go into `HBASE_HEAPSIZE`).
Actually they are role specific, so they do *not* go into HBASE_OPTS.
Instead they go into `HBASE_MASTER_OPTS` and others

Maybe something like
```
/// JVM arguments that are specifically for the role (server), so will *not* be used e.g. by CLI tools.
/// Heap settings are excluded, as they go into `HBASE_HEAPSIZE`.
```