Fix bug where the configuration of the hbaseRootdir at the role level is ignored
stackabletech/hbase-operator pull request #584
Opened 2024-11-13 14:41 UTC by maltesander

# Description

The problem was defaulting in the product config callbacks like:

```
 result.insert( 
     HBASE_ROOTDIR.to_string(), 
     Some( 
         self.hbase_rootdir 
             .as_deref() 
             .unwrap_or(HBASE_ROOT_DIR_DEFAULT) 
             .to_string(), 
     ), 
 ); 
```

If the `hbaseRootdir` was only set on the role, we defaulted the rolegroup to `HBASE_ROOT_DIR_DEFAULT` ("/hbase"), which during merging overrode the value set on the role. The solution here is to remove the defaulting and it works.
One problem remained, if `hbaseRootdir` was not set at all, there was no default set anymore. The product config did not add the default due to the field being marked as not required.
In order to keep the defaulting behavior as is and not mess with existing defaulted installation, the default for `hbase.root.dir` in the product config was changed to "/hbase" and the field marked as required (on all roles).
The docs state though:
```
The directory shared by region servers and into which HBase persists. The URL should be 'fully-qualified' to include the filesystem scheme. For example, to specify the HDFS directory '/hbase' where the HDFS instance's namenode is running at namenode.example.org on port 9000, set this value to: hdfs://namenode.example.org:9000/hbase. By default, we write to whatever ${hbase.tmp.dir} is set too -- usually /tmp -- so change this configuration or else all data will be lost on machine restart.
```

So i think we can only use it on the regionservers? Ping @lfrancke 

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

2024-11-15 11:14 UTC, siegfriedweber requested changes

2024-11-15 11:14 UTC, siegfriedweber commented on deploy/config-spec/properties.yaml
> +          required: true # TODO: this could be false?
Only the `hbase.rootdir` is effective which is configured at the master. The other ones are ignored.

2024-11-15 12:36 UTC, maltesander commented on rust/crd/src/lib.rs
> -                            .unwrap_or(HBASE_ROOT_DIR_DEFAULT)
good point, done https://github.com/stackabletech/hbase-operator/pull/584/commits/28b556c67c3a633be8f1b6d088783471a7d412fc

2024-11-15 14:22 UTC, maltesander commented on deploy/config-spec/properties.yaml
> +          required: true # TODO: this could be false?
improved/corrected comments https://github.com/stackabletech/hbase-operator/pull/584/commits/1095505a4371acfaa0c2b9adbabf825c3f90ee6a and keep restserver and and regionserver true for compatibility reasons.

2024-11-15 16:18 UTC, siegfriedweber approved these changes
LGTM

2024-11-15 16:22 UTC, merged

2024-11-17 15:39 UTC, lfrancke commented
I'm a bit confused by the comment. That seems to indicate that it's not required by the RegionServer?

2024-11-17 19:02 UTC, siegfriedweber commented
> I'm a bit confused by the comment. That seems to indicate that it's not required by the RegionServer?

The master apparently tells the RegionServers where the root dir is located. I have not checked this assumption in the code but I tested it:

If I set different root dirs for the roles ...

```diff
$ git diff
diff --git a/tests/templates/kuttl/smoke/30-install-hbase.yaml.j2 b/tests/templates/kuttl/smoke/30-install-hbase.yaml.j2
index ac1bed8..ea5d883 100644
--- a/tests/templates/kuttl/smoke/30-install-hbase.yaml.j2
+++ b/tests/templates/kuttl/smoke/30-install-hbase.yaml.j2
@@ -21,6 +21,7 @@ spec:
 {% endif %}
   masters:
     config:
+      hbaseRootdir: /rtmaster
       logging:
         enableVectorAgent: {{ lookup('env', 'VECTOR_AGGREGATOR') | length > 0 }}
     roleGroups:
@@ -32,6 +33,7 @@ spec:
         replicas: 2
   regionServers:
     config:
+      hbaseRootdir: /rtregion
       logging:
         enableVectorAgent: {{ lookup('env', 'VECTOR_AGGREGATOR') | length > 0 }}
     roleGroups:
@@ -43,6 +45,7 @@ spec:
         replicas: 2
   restServers:
     config:
+      hbaseRootdir: /rtrest
       logging:
         enableVectorAgent: {{ lookup('env', 'VECTOR_AGGREGATOR') | length > 0 }}
     roleGroups:
```

... then the one set for the master is effective:

```shell
$ bin/hdfs dfs -fs hdfs://test-hdfs/ -ls /
Found 1 items
drwxr-xr-x   - stackable supergroup          0 2024-11-15 11:00 /rtmaster
$ bin/hdfs dfs -fs hdfs://test-hdfs/ -ls /rtmaster
Found 12 items
drwxr-xr-x   - stackable supergroup          0 2024-11-15 11:00 /rtmaster/.hbck
drwxr-xr-x   - stackable supergroup          0 2024-11-15 11:00 /rtmaster/.tmp
drwxr-xr-x   - stackable supergroup          0 2024-11-15 11:00 /rtmaster/MasterData
drwxr-xr-x   - stackable supergroup          0 2024-11-15 11:00 /rtmaster/WALs
drwxr-xr-x   - stackable supergroup          0 2024-11-15 11:10 /rtmaster/archive
drwxr-xr-x   - stackable supergroup          0 2024-11-15 11:00 /rtmaster/corrupt
drwxr-xr-x   - stackable supergroup          0 2024-11-15 11:01 /rtmaster/data
-rw-r--r--   3 stackable supergroup         42 2024-11-15 11:00 /rtmaster/hbase.id
-rw-r--r--   3 stackable supergroup          7 2024-11-15 11:00 /rtmaster/hbase.version
drwxr-xr-x   - stackable supergroup          0 2024-11-15 11:00 /rtmaster/mobdir
drwxr-xr-x   - stackable supergroup          0 2024-11-15 11:00 /rtmaster/oldWALs
drwx--x--x   - stackable supergroup          0 2024-11-15 11:00 /rtmaster/staging
```

2024-11-18 08:15 UTC, maltesander commented
To add to this, we (or I?) decided to still set the `hbaseRootdir` on the region and rest server (even if not required) in order to keep existing "functionality" or at least avoid restarts in exitsting installations due to config changes.