feat: `requestedSecretLifetime` role group property added
stackabletech/hbase-operator pull request #598
Opened 2024-11-28 16:06 UTC by razvan

# Description

Depends on: https://github.com/stackabletech/operator-rs/pull/915

Part of: https://github.com/stackabletech/issues/issues/586
 
## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

2024-11-29 07:50 UTC, sbernauer commented on rust/operator-binary/src/hbase_controller.rs
> +                .unwrap_or(DEFAULT_SECRET_LIFETIME),
I would prefer to error out (technically it would be allowed to panic here, as it's a bug - but let's use a snafu just to be safe) in case it is not set.
As the default set's it to Some(value), if it is missing here that's a bug. Going forward we will not have one default for all rolegroups (so it will get more complicated) and we ideally only have defaults at one place in code.
With that arguments I would prefer having a `.context(ThisMustBeSetHereSnafu)?` (with better error name) instead.

Unrelated: Is this a `merged_config` or the config from the role or the group? After making sure it's the merged on, can we please rename it to `merged_config` (as in other operators)?. Because only taking it from the role or rolegroup would be wrong and result in yet another "it works on rolegroups but not on roles" bug.

2024-11-29 07:56 UTC, sbernauer requested changes
Was a bit more picky here, as it's probably the template PR for other operators and I don't want you to have problems mid-way

2024-11-29 07:56 UTC, sbernauer commented on rust/crd/src/lib.rs
> +    /// Request secret (currently only auto certificates) lifetime from the secret operator.
```suggestion
    /// Request secret (currently only autoTls certificates) lifetime from the secret operator, e.g. `7d`, or `30d`.
    /// Please note that this can be shortened by the `maxCertificateLifetime` setting on the SecretClass issuing the TLS certificate.
```

2024-11-29 07:56 UTC, sbernauer commented on CHANGELOG.md
> +- Lifetime of auto generated certificates is configurable with the `requestedSecretLifetime` role group property ([#598])
```suggestion
- The lifetime of auto generated TLS certificates is now configurable with the role and roleGroup config property `requestedSecretLifetime` ([#598])
```

2024-11-29 08:00 UTC, sbernauer commented on rust/crd/src/lib.rs
> +pub const DEFAULT_SECRET_LIFETIME: Duration = Duration::from_days_unchecked(7);
I would also prefer to remove this constant and only let `default_config` decide on the default value. This is especially important going forward with operators having different defaults for roles

2024-11-29 08:51 UTC, razvan commented on rust/operator-binary/src/hbase_controller.rs
> +                .unwrap_or(DEFAULT_SECRET_LIFETIME),
yes, it's the `merged_config` structure. [fixed](https://github.com/stackabletech/hbase-operator/pull/598/commits/2d3681265262f697ab7362741086489d5b22d0f6)

2024-11-29 08:51 UTC, razvan commented on rust/crd/src/lib.rs
> +pub const DEFAULT_SECRET_LIFETIME: Duration = Duration::from_days_unchecked(7);
[done](https://github.com/stackabletech/hbase-operator/pull/598/commits/2d3681265262f697ab7362741086489d5b22d0f6)

2024-11-29 14:44 UTC, sbernauer commented on rust/crd/src/lib.rs
> +pub const DEFAULT_SECRET_LIFETIME: Duration = Duration::from_days_unchecked(7);
I have to admit I was thinking of removing the constants entirely, so that no one actually does a .unwrap_or(CONSTANT) going forward (which always has the chance of introducing a bug).
If we don't have a constant, no one can accidentally use it when really the default should be coming from `default_config`.

What do you think of this? This is an objective thing and I don't want to force you to do it as I say. Just in case you are happy with the proposal:
```diff
diff --git a/rust/crd/src/lib.rs b/rust/crd/src/lib.rs
index 0a74cee..021d690 100644
--- a/rust/crd/src/lib.rs
+++ b/rust/crd/src/lib.rs
@@ -81,16 +81,6 @@ pub const METRICS_PORT: u16 = 9100;
 
 pub const JVM_HEAP_FACTOR: f32 = 0.8;
 
-const DEFAULT_MASTER_GRACEFUL_SHUTDOWN_TIMEOUT: Duration = Duration::from_minutes_unchecked(20);
-const DEFAULT_REGION_SERVER_GRACEFUL_SHUTDOWN_TIMEOUT: Duration =
-    Duration::from_minutes_unchecked(60);
-const DEFAULT_REST_SERVER_GRACEFUL_SHUTDOWN_TIMEOUT: Duration = Duration::from_minutes_unchecked(5);
-
-// Auto TLS certificate lifetime
-const DEFAULT_MASTER_SECRET_LIFETIME: Duration = Duration::from_days_unchecked(7);
-const DEFAULT_REGION_SECRET_LIFETIME: Duration = Duration::from_days_unchecked(7);
-const DEFAULT_REST_SECRET_LIFETIME: Duration = Duration::from_days_unchecked(7);
-
 #[derive(Snafu, Debug)]
 pub enum Error {
     #[snafu(display("the role [{role}] is invalid and does not exist in HBase"))]
@@ -309,16 +299,11 @@ impl HbaseRole {
         };
 
         let graceful_shutdown_timeout = match &self {
-            HbaseRole::Master => Some(DEFAULT_MASTER_GRACEFUL_SHUTDOWN_TIMEOUT),
-            HbaseRole::RegionServer => Some(DEFAULT_REGION_SERVER_GRACEFUL_SHUTDOWN_TIMEOUT),
-            HbaseRole::RestServer => Some(DEFAULT_REST_SERVER_GRACEFUL_SHUTDOWN_TIMEOUT),
-        };
-
-        let requested_secret_lifetime = match &self {
-            HbaseRole::Master => Some(DEFAULT_MASTER_SECRET_LIFETIME),
-            HbaseRole::RegionServer => Some(DEFAULT_REGION_SECRET_LIFETIME),
-            HbaseRole::RestServer => Some(DEFAULT_REST_SECRET_LIFETIME),
+            HbaseRole::Master => Duration::from_minutes_unchecked(20),
+            HbaseRole::RegionServer => Duration::from_minutes_unchecked(60),
+            HbaseRole::RestServer => Duration::from_minutes_unchecked(5),
         };
+        let requested_secret_lifetime = Duration::from_days_unchecked(7);
 
         HbaseConfigFragment {
             hbase_rootdir: None,
@@ -326,8 +311,8 @@ impl HbaseRole {
             resources,
             logging: product_logging::spec::default_logging(),
             affinity: get_affinity(cluster_name, self, hdfs_discovery_cm_name),
-            graceful_shutdown_timeout,
-            requested_secret_lifetime,
+            graceful_shutdown_timeout: Some(graceful_shutdown_timeout),
+            requested_secret_lifetime: Some(requested_secret_lifetime),
         }
     }
```

2024-11-29 14:49 UTC, sbernauer requested changes
Finally got the time to review it properly, sorry! Only one code comment left.

Can we please rename the PRs to something a bit more user-facing? E.g. `feat: Support setting TLS certificate lifetimes` or `feat: Support setting TLS certificate lifetimes to avoid frequent Pod restarts`

2024-11-29 14:49 UTC, sbernauer commented on CHANGELOG.md
> +- The lifetime of auto generated TLS certificates is now configurable with the role and roleGroup config property `requestedSecretLifetime` ([#598])
```suggestion
- The lifetime of auto generated TLS certificates is now configurable with the role and roleGroup
  config property `requestedSecretLifetime`. This helps reducing frequent Pod restarts ([#598]).
```

2024-11-29 15:16 UTC, razvan commented on rust/crd/src/lib.rs
> +pub const DEFAULT_SECRET_LIFETIME: Duration = Duration::from_days_unchecked(7);
I personally think this makes the code more obfuscated for future readers.

Named constants can also document _why_ we choose different values.

The consts are already module private but they can be moved even lower in the structure to reduce accidental (re)use.

2024-12-02 08:37 UTC, sbernauer commented on rust/crd/src/lib.rs
> +pub const DEFAULT_SECRET_LIFETIME: Duration = Duration::from_days_unchecked(7);
Ok, I don't have a problem with constants per se :sweat_smile: I think moving them to a lower code structure seems like a fair compromise.
What do you think of that?
```diff
diff --git a/rust/crd/src/lib.rs b/rust/crd/src/lib.rs
index 0a74cee..e9930e7 100644
--- a/rust/crd/src/lib.rs
+++ b/rust/crd/src/lib.rs
@@ -81,16 +81,6 @@ pub const METRICS_PORT: u16 = 9100;
 
 pub const JVM_HEAP_FACTOR: f32 = 0.8;
 
-const DEFAULT_MASTER_GRACEFUL_SHUTDOWN_TIMEOUT: Duration = Duration::from_minutes_unchecked(20);
-const DEFAULT_REGION_SERVER_GRACEFUL_SHUTDOWN_TIMEOUT: Duration =
-    Duration::from_minutes_unchecked(60);
-const DEFAULT_REST_SERVER_GRACEFUL_SHUTDOWN_TIMEOUT: Duration = Duration::from_minutes_unchecked(5);
-
-// Auto TLS certificate lifetime
-const DEFAULT_MASTER_SECRET_LIFETIME: Duration = Duration::from_days_unchecked(7);
-const DEFAULT_REGION_SECRET_LIFETIME: Duration = Duration::from_days_unchecked(7);
-const DEFAULT_REST_SECRET_LIFETIME: Duration = Duration::from_days_unchecked(7);
-
 #[derive(Snafu, Debug)]
 pub enum Error {
     #[snafu(display("the role [{role}] is invalid and does not exist in HBase"))]
@@ -267,6 +257,17 @@ pub enum HbaseRole {
 }
 
 impl HbaseRole {
+    const DEFAULT_MASTER_GRACEFUL_SHUTDOWN_TIMEOUT: Duration = Duration::from_minutes_unchecked(20);
+    const DEFAULT_REGION_SERVER_GRACEFUL_SHUTDOWN_TIMEOUT: Duration =
+        Duration::from_minutes_unchecked(60);
+    const DEFAULT_REST_SERVER_GRACEFUL_SHUTDOWN_TIMEOUT: Duration =
+        Duration::from_minutes_unchecked(5);
+
+    // Auto TLS certificate lifetime
+    const DEFAULT_MASTER_SECRET_LIFETIME: Duration = Duration::from_days_unchecked(7);
+    const DEFAULT_REGION_SECRET_LIFETIME: Duration = Duration::from_days_unchecked(7);
+    const DEFAULT_REST_SECRET_LIFETIME: Duration = Duration::from_days_unchecked(7);
+
     pub fn default_config(
         &self,
         cluster_name: &str,
@@ -309,15 +310,15 @@ impl HbaseRole {
         };
 
         let graceful_shutdown_timeout = match &self {
-            HbaseRole::Master => Some(DEFAULT_MASTER_GRACEFUL_SHUTDOWN_TIMEOUT),
-            HbaseRole::RegionServer => Some(DEFAULT_REGION_SERVER_GRACEFUL_SHUTDOWN_TIMEOUT),
-            HbaseRole::RestServer => Some(DEFAULT_REST_SERVER_GRACEFUL_SHUTDOWN_TIMEOUT),
+            HbaseRole::Master => Some(Self::DEFAULT_MASTER_GRACEFUL_SHUTDOWN_TIMEOUT),
+            HbaseRole::RegionServer => Some(Self::DEFAULT_REGION_SERVER_GRACEFUL_SHUTDOWN_TIMEOUT),
+            HbaseRole::RestServer => Some(Self::DEFAULT_REST_SERVER_GRACEFUL_SHUTDOWN_TIMEOUT),
         };
 
         let requested_secret_lifetime = match &self {
-            HbaseRole::Master => Some(DEFAULT_MASTER_SECRET_LIFETIME),
-            HbaseRole::RegionServer => Some(DEFAULT_REGION_SECRET_LIFETIME),
-            HbaseRole::RestServer => Some(DEFAULT_REST_SECRET_LIFETIME),
+            HbaseRole::Master => Some(Self::DEFAULT_MASTER_SECRET_LIFETIME),
+            HbaseRole::RegionServer => Some(Self::DEFAULT_REGION_SECRET_LIFETIME),
+            HbaseRole::RestServer => Some(Self::DEFAULT_REST_SECRET_LIFETIME),
         };
 
         HbaseConfigFragment {
```

2024-12-02 10:44 UTC, razvan commented on rust/crd/src/lib.rs
> +pub const DEFAULT_SECRET_LIFETIME: Duration = Duration::from_days_unchecked(7);
[applied](https://github.com/stackabletech/hbase-operator/pull/598/commits/9cdf652ddacf5c101d954c9f02fd22aed643c96e)

2024-12-02 11:18 UTC, sbernauer approved these changes
Code LGTM (one nit). Please wait with merging until the decision https://github.com/stackabletech/issues/issues/673 is approved

2024-12-02 11:18 UTC, sbernauer commented on rust/crd/src/lib.rs
> +            requested_secret_lifetime,
nit (optional): I would suggest using the Some() here (instead of above), so that it is enforced that every possible code path produces a valid non-default value. But if you have stronger feelings, please ignore :sweat_smile: 
```suggestion
            graceful_shutdown_timeout: Some(graceful_shutdown_timeout),
            requested_secret_lifetime: Some(requested_secret_lifetime),
```

2024-12-02 12:10 UTC, razvan commented on rust/crd/src/lib.rs
> +            requested_secret_lifetime,
I don't have strong feelings but I don't understand. What code path can lead to an invalid value?

2024-12-02 13:00 UTC, sbernauer commented on rust/crd/src/lib.rs
> +pub const DEFAULT_SECRET_LIFETIME: Duration = Duration::from_days_unchecked(7);
Thanks!

2024-12-02 13:02 UTC, sbernauer commented on rust/crd/src/lib.rs
> +            requested_secret_lifetime,
If we do it like this
```diff
diff --git a/rust/crd/src/lib.rs b/rust/crd/src/lib.rs
index e9930e7..321b1d3 100644
--- a/rust/crd/src/lib.rs
+++ b/rust/crd/src/lib.rs
@@ -310,15 +310,15 @@ impl HbaseRole {
         };
 
         let graceful_shutdown_timeout = match &self {
-            HbaseRole::Master => Some(Self::DEFAULT_MASTER_GRACEFUL_SHUTDOWN_TIMEOUT),
-            HbaseRole::RegionServer => Some(Self::DEFAULT_REGION_SERVER_GRACEFUL_SHUTDOWN_TIMEOUT),
-            HbaseRole::RestServer => Some(Self::DEFAULT_REST_SERVER_GRACEFUL_SHUTDOWN_TIMEOUT),
+            HbaseRole::Master => Self::DEFAULT_MASTER_GRACEFUL_SHUTDOWN_TIMEOUT,
+            HbaseRole::RegionServer => Self::DEFAULT_REGION_SERVER_GRACEFUL_SHUTDOWN_TIMEOUT,
+            HbaseRole::RestServer => Self::DEFAULT_REST_SERVER_GRACEFUL_SHUTDOWN_TIMEOUT,
         };
 
         let requested_secret_lifetime = match &self {
-            HbaseRole::Master => Some(Self::DEFAULT_MASTER_SECRET_LIFETIME),
-            HbaseRole::RegionServer => Some(Self::DEFAULT_REGION_SECRET_LIFETIME),
-            HbaseRole::RestServer => Some(Self::DEFAULT_REST_SECRET_LIFETIME),
+            HbaseRole::Master => Self::DEFAULT_MASTER_SECRET_LIFETIME,
+            HbaseRole::RegionServer => Self::DEFAULT_REGION_SECRET_LIFETIME,
+            HbaseRole::RestServer => Self::DEFAULT_REST_SECRET_LIFETIME,
         };
 
         HbaseConfigFragment {
@@ -327,8 +327,8 @@ impl HbaseRole {
             resources,
             logging: product_logging::spec::default_logging(),
             affinity: get_affinity(cluster_name, self, hdfs_discovery_cm_name),
-            graceful_shutdown_timeout,
-            requested_secret_lifetime,
+            graceful_shutdown_timeout: Some(graceful_shutdown_timeout),
+            requested_secret_lifetime: Some(requested_secret_lifetime),
         }
     }
```
You can directly tell `graceful_shutdown_timeout` and `requested_secret_lifetime` are always set as a default value, no matter what.
With the current state you would need to look at the code above to be sure that it is always set, and operators can rely on the value always being `Some`.

But it's a nit

2024-12-02 15:44 UTC, razvan commented on rust/crd/src/lib.rs
> +            requested_secret_lifetime,
[applied](https://github.com/stackabletech/hbase-operator/pull/598/commits/8c4387ae85fd5c296c1edfe734c5635d33f7dd68)

2024-12-03 07:46 UTC, sbernauer commented on rust/crd/src/lib.rs
> +            requested_secret_lifetime,
Thanks!

2024-12-03 07:53 UTC, sbernauer submitted a review, later dismissed
Thanks!
Code LGTM. Please wait with merging until the decision https://github.com/stackabletech/issues/issues/673 is approved

2024-12-04 07:25 UTC, sbernauer approved these changes
Thanks!

2024-12-04 07:26 UTC, sbernauer commented
It would be awesome if you could run `cargo update` to get the CI green ;)

2024-12-04 08:25 UTC, sbernauer approved these changes
Wuhuuuu!

2024-12-04 08:43 UTC, merged